services:
  jekyll:
    image: bretfisher/jekyll-serve
    volumes:
      - .:/site
    ports:
      - "4000:4000"

  esbuild:
    image: node:22-alpine
    volumes:
      - .:/site
      - /site/node_modules
    working_dir: /site
    tty: true
    stdin_open: true
    restart: always
    command: sh -c "npm install && npm run watch"
